bin.includes = META-INF/,\
               LICENSE.txt,\
               plugin.xml,\
               img/,\
               plugin.properties,\
               com.archimatetool.modelrepository.jar,\
               logging.properties,\
               help/,\
               lib/org.eclipse.jgit.gpg.bc_6.10.0.202406032230-r.jar
output.com.archimatetool.modelrepository.jar = bin/
source.com.archimatetool.modelrepository.jar = src/
